services:
  postgres:
    image: postgres:16
    container_name: biblioteca-postgres
    restart: always
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: biblioteca_user
      POSTGRES_PASSWORD: biblioteca_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biblioteca_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
