[project]
name = "biblioteca-back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.123.0",
    "psycopg2-binary>=2.9.11",
    "pymysql>=1.1.2",
    "sqlmodel>=0.0.27",
]
